### PR TITLE
Strip vendor

### PR DESCRIPTION
**Pull request by guilhem**
Use `glide install -v`
This make repository really standalone

### CODE REVIEW

**Comment by kobolog** [comment]
Hey @guilhem, I like this change! If you make it work with Travis, I'll merge it right away.

**Comment by guilhem** [comment]
@kobolog on my way ;)

**Comment by guilhem** [comment]
@kobolog should be ok + adding test (who can fail...)

**Comment by kobolog** [comment]
Thank you!

**Comment by guilhem** [comment]
@kobolog don't forget to replace `MY_KEY` by your key.
You can use `travis` CLI to do this :)

**Comment by kobolog** [comment]
Will do, thanks for pointing this out =)

**Pull request merged**
