### PR TITLE
Fix vendored dependencies

### PR DESCRIPTION
**Pull request by jsravn**
Remove 'vendor' from gitignore, and add stretchr dep that was previously
added. Also remove `glide install -v` to catch broken vendor folder.

`vendor` got added to gitignore in a previous commit but the vendor folder was not removed, which was pretty confusing when trying to do dev. We could either remove vendor completely, or restore the prior behaviour which is what I've done here.

### CODE REVIEW

**Comment by kobolog** [comment]
I think removing `vendor` and relying on `glide install` is better from the perspective of repo pollution. Dependencies are still going to have their revisions fixed in `glide.lock` but the repo won't be cluttered with all these unrelated files. What do you think?

**Comment by jsravn** [comment]
Removing vendor makes dev slightly more painful - need to remember to glide install on git pull. So I usually prefer having vendor. But I don't feel that strongly about it. It's more important we either fix vendor or remove it completely. If you'd like I can remove it.

**Comment by kobolog** [comment]
I think `glide install` is cleaner and I generally don't like clutter in the repo =)

**Comment by jsravn** [comment]
@kobolog Okay, I made https://github.com/kobolog/gorb/pull/53 for it.

**Pull request closed without merging**
